select count(*) LOT_BF_LISTING  from LOT_BF_LISTING where ID IN(SELECT OK_MATCH_ID FROM LOT_MATCH where OK_URL_DATE like '1409%');
select count(*) LOT_ALL_AVERAGE from LOT_ALL_AVERAGE where ID IN(SELECT OK_MATCH_ID FROM LOT_MATCH where OK_URL_DATE like '1409%');
select count(*) LOT_TRANS_PROP from LOT_TRANS_PROP where ID IN(SELECT OK_MATCH_ID FROM LOT_MATCH where OK_URL_DATE like '1409%');
select count(*) LOT_BF_TURNOVER_DETAIL from LOT_BF_TURNOVER_DETAIL where ID IN(SELECT OK_MATCH_ID FROM LOT_MATCH where OK_URL_DATE like '1409%');
select count(*) LOT_ODDS_EURO from LOT_ODDS_EURO where OK_MATCH_ID IN(SELECT OK_MATCH_ID FROM LOT_MATCH where OK_URL_DATE like '1409%');
select count(*) LOT_ODDS_ASIA from LOT_ODDS_ASIA where OK_MATCH_ID IN(SELECT OK_MATCH_ID FROM LOT_MATCH where OK_URL_DATE like '1409%');
select count(*) LOT_ODDS_EURO_CHANGE from LOT_ODDS_EURO_CHANGE where OK_MATCH_ID IN(SELECT OK_MATCH_ID FROM LOT_MATCH where OK_URL_DATE like '1409%');
select count(*) LOT_ODDS_ASIA_CHANGE from LOT_ODDS_ASIA_CHANGE where OK_MATCH_ID IN(SELECT OK_MATCH_ID FROM LOT_MATCH where OK_URL_DATE like '1409%');
select count(*) LOT_MATCH from LOT_MATCH where OK_URL_DATE like '1409%';
select count(distinct OK_MATCH_ID) from LOT_ODDS_EURO_CHANGE where OK_MATCH_ID in(select OK_MATCH_ID FROM LOT_MATCH where ok_url_date like '1409%')
